/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData recent = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notification = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData logOut = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData myLocation = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe806, fontFamily: _kFontFam);
}
